### ISSUE TITLE
Airgap / Multisig Integration

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#2866] opened 2024-03-21 08:51 UTC
We need to use Airgap Vault with SH Wallet. 

More specific accounts stored in Airgap Vault could be used. 
User should be able to sign transactions though his vault.
User should be able to provide concensus in a multisig transaction though his vault. 

Airgap Vault shall be usable in online/offline mode.

**Comment by martinkaintas** [comment] 2024-05-13 08:54
>if I'm clicking on Pair QR wallet it opens camera instead, however as I understood from the screen it should show QR code (Scan this QR code from your AirGap vault in order to pair wallets and import accounts - probably word 'this" is leading to misunderstanding) :

This is implemented according to Figma but I agree that it is confusing
@onvisions Can you take a look?

**Comment by Liubov-crypto** [comment] 2024-05-13 15:40
Updated my comments: 
1. I've added account from airgap vault using QR scanner code.

2. I was trying to create multisig vault and using imported airgap acc as 1st signer, but nothing happened when I scan QR on the second step:

https://github.com/superhero-com/superhero-wallet/assets/69896204/372c3e69-de25-4852-90a4-4c35e82862d3

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/1a13180b-1ef6-43c1-b7b2-b8da6edce0ca)


but if airgap account will be second signer I will be able to create a vault

3. I was proposing Tx from my vault and trying to approve it but got an issue (second signer is my imported AE airgap vault account):


https://github.com/superhero-com/superhero-wallet/assets/69896204/db6b7c25-de53-42a5-8e95-a6c486516580


![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/92240634-1268-4feb-85ba-b8d8863eafe8)

btw, I opened my airgap vault but can't see any pending tx for approval...how this should work? 

4. I was sending Tx from my imported airgap ae account, Tx was confirmed in airgap vault but stuck on step when I was trying to scan again qr from vault by wallet scan:

https://github.com/superhero-com/superhero-wallet/assets/69896204/8c19a38e-375d-491b-8e3f-c72fc97fab86

some broken logic here, why should I click on scan button and scan qr if I've already confirmed tx in my airgap vault? 

After I confirmed Tx in airgap vault I have to switch to airgap wallet to sent Tx. In other case ut will not working.

**Comment by Liubov-crypto** [comment] 2024-05-14 13:42
I found an interesting case with imported airgap account - when user is trying to register a name, I was able to preclaim it, but on the final step signing the tx in airgap vault was not successful (the same issue with scan qr code). I think there is the same case as with sending Tx, we need one additional step to split qr code and scan button:

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/3cc8a7df-163e-4c66-a1a9-b2a188ea211b)

**Comment by Liubov-crypto** [comment] 2024-05-15 13:49
1. I've tested new version and it works fine with imported airgap vault account if I want to send tx. Minor proposal: 
- delete scan icon from Next button
- add info that user have to scan V3 QR code, not V2 which opens by default in airgap vault

what do you think @onvisions @martinkaintas ? 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/70e1ad66-16b8-4fe3-8ba5-acffc70bde0f)



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/2e75249d-50cd-470a-b873-02d00e80d333)



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/a3dd5e99-3a84-4d31-ab7b-6837fce79c80)

2. If I want to register a name with imported airgap account I will stuck on scan qr code from vault, it will not work not V3 nor V2:



https://github.com/superhero-com/superhero-wallet/assets/69896204/8dc84bec-cb2f-4b5f-b206-f634d09ddb30



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/7b144952-5782-4e6a-9428-dc11e1c2e3b9)

3. The same error is for creating multisig using airgap account:



https://github.com/superhero-com/superhero-wallet/assets/69896204/2fdb3d24-2baf-4f45-90a0-6c17d6905f7f



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/924f7371-ea16-4dfc-9e9c-bcf8f6bcd67e)

**Comment by Liubov-crypto** [comment] 2024-05-22 14:37
1. Sending Tx from imported vault account works fine for me. 

2. If I want register a chain name using imported vault account it will throw me at 1st step again after I confirmed 2nd step in my airgap vault, however I was managed to register one name from 3rd attempt, but this case should be investigated:


https://github.com/superhero-com/superhero-wallet/assets/69896204/ba750e0f-c34c-4e55-9f75-6f008529592f



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/4c022b02-9932-4602-88be-0f0c90d2e2c4)



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/b7a79427-9d87-4a99-b291-af9d2dba9bc5)







![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/2f11e4af-7230-4b32-ae82-93842966c7b6)



3.  it seems that copy - paste multiply codes from airgap vault into wallet isn't working when I want to create multisig vault using imported airgap account as 1st signer. I think this is because prefix like airgap-wallet://?ur= for text qr code is missing: 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/e0c82b14-c54b-445a-9a79-9981775f5ae9)


The same steps via scanning qr codes are working, however it can takes a lot of time to scan multiply codes from airgap and could be painful for user (at least for me and my old mac :'( ) 


4. It seems that text on this modal isn't correct, I just want to sign Tx via airgap vault to send it via multisig account, not pair the account, @onvisions  @martinkaintas what do you think guys? 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/f62e4c72-1cea-46a5-ba8a-ba8e87d7d24b)

**Comment by Liubov-crypto** [comment] 2024-05-22 14:42
One more visual issue but this is airgap side, @smaroudasunicorn probably it's worth to contact airgap team to fix it: 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/8f56971b-3a82-4bfd-8edf-c1114a55045f)

**Comment by Liubov-crypto** [comment] 2024-05-23 09:45
1. I can't make by default a name in my imported airgap account: 



https://github.com/superhero-com/superhero-wallet/assets/69896204/7f68a41f-aebe-451f-ab86-f7c138f4b796



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/3541ed33-8e56-4c4e-8549-444518327b8d)



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/7f82d656-ac8e-4869-bbe5-6bbdd541371d)



but probably this is out of scope and we should track this separately 

2. When I want to create multisig vault using imported airgap account as first signer, on first step I have to sign tx via scan qr code using vault or copy/paste it. Copy/paste function isn't working, airgap vault doesn't recognise it: 



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/8ef2eeae-77b8-4eab-84f5-5ac12a1f0559)

example of copy/paste code: 

UR:BYTES/HKBAGTCTLUAYAEAEAEAEAEAEAXMDHDSBPLWFHTGMCMLGKNTDBGBGFSFWIDKOCSDYSORTMNMUWPSSFDLATBPRMSJLLDCAURJLBNHTRNDKMNIAFRTOUTGAAMFDOSHPGSMEKSAHHYLAVAAHMKEYOECTOEKKBNDSTYJPPRYLTAZMLBTOURTDLDQZVEETWNPKGOGOHETLHGGOZEWENELBZMDLLBYNSBEEHKZCYKDLZEVAFHVARSJEGWMSZCWDROHKCAUYRSIAMKLBSFZMFMZTWYCHUYZMZOWYHGURZMWNYLSTURZMVYLBKBYKBSZMZEMSZMYNLTWSKBCFZCSKLBZETEWSZEYTZOZMZCYKLBZCWNJLZMYKRLUYIEYKNDDSDTKTRKTLYTZEHGZMKIRNZCIYHNDNRDHGSPCWBBCEOSPKKPRTVLCNRNNEWKPTCLJZURGEOEDTGRTLWZIAEHMDTDIDWKLNSTEMKKDYDMMUONCEFEBGKONDJNLULRASLDFLPFTNAHHTJLLRBDSESBYTGYCXBSIYWFRTCXMYAYSBCWVLKPVYEEHNMULERFUTLTJEGLHFBBKBSAPFVDHDKBCEYKDNPYHYVAOSKOFNJTTOWLDMWYUETNLYNNGWGOLFBSRDHFAYVYNTRKFLCNIEWFMTJSPADAKGHNGRGRBSGYFSGTMYRLEMVAUYIERLGTHGGLJSIMMOOTWMTKBBRPLGLFWZPANDLOTLBBNTVAYKETNSUOKODEPMPSUTRDPRNYDRBGUYSKVSCYMKFMBYAMIHMDLOEOIHVSFTCLLEQDSTOEIABKHFCKHHNLSTTDDPPMSNRHMUFNREHPGHHFRDPDLKESEOCMNLPMFNFXIDLNLKPLGHTIMTHYVWTIFWTATOWYBEHLCLRNPMHYRSGRBKSAWECEPTMEIMRPMELAGYDICKSTDRFWCMIDFYEEDICPTDSKVDEYVTHYFLTKWMWZHTBBAYCNJSRPBWEHFWYNRPBZBEFWVTGSDKTPVAMKPDCABGGDOYSAKIAAHGUTJTSKKEMYLUNLCXAYSKGAFZPKLAJTJPHSJOMDDWKOWDHHOXYLWTGSRHTSPKBDFNCNOEMNWYBZSOWDVSSOPAIHOEBTMDJEGYRHTOGRPLMNBKGRFLDPPSOELATLSAWDVTCFBZYNPKCMDWFLWMFTBDNLIAGANDKSDATPDETYPSFZJNSKYATTDLPFLYWKIOMOFDUTDTUTGSFZMOYLFNTEGTYAJNIOYAAYSEYLHHBBTEFEHSSAHKNBDLVYPLTTGSAAKIIHTPBDZOGORDVSKKVTCTGOLNWFVARPYTDSLBVSIOLYOTKNFSEHHSGHHLSWNBLBDLOSFZWTHLRLVLDKDWFYIYFNYLSWPSAXCSVYNYFECNAAKBBSFSURWNDRUEASTAASCXRNTTUODRHEZOLRHEKGMDCTROWPHKAOFNIEPKYLHNWSNSJZPKEMYKBZWDDYVSMYVSWSSAWPNBCKVTYLJYPSENMYKGJSSAAYZONBBYSAHLOSBAFTOTRPKISNJSLTTNTNIDDAUTDAZEWFCELDRLVTGSSBCACYMOHGCMDIRTMENBNDGHIESTWEMNDTPLWFJPKBBGLKTOGDMHMTFXPSAABEFXRHLFIEHDBEHPEHGRVLOSTSHLDEBKTIOTYLNDFNLETKMTAOETWDISEEMUGYCHSEYLVLBBBTDASOPYECTEPYYTONFRQZTSMTWSKGBAVYCASTURGRENCPOEKKDLEYAYRDLFLAFHGYMSBAFYUOVAESMDPMIECSRETESEBWDNKPLROEBNWKCLBKHLRODNKSETMUTPUYAYTYSWEHSAHFADHGTALAFRRTURHEFSAMEYSKZMHPKNVLETFLMKKIRSSTEEDLFGWKLBLEWNDIFNHPAHVOTNRLRNSWGMDATYVDFSMTFHYAFNSRAHWPRHGAHPDLQZTKDRDRASYKFSPRJYIYMNFRLRDRKTHFJYBYSEBEFRZCOEEYJTGMRYHECLMUTADMJTRHGORYZTNLDPSBSANTOELDZMWYEOTAYNZTREDIINBECHRNVSMUTNJYJECKRKMODSHKNNCALTPSPMKKPSDKAEOLBEMYJKTIMDWDNBTPIODMYKVTZTESHNRSKKSTUEPMKSDLIEONREHEGARDVLTAJEMYPMBZRLWZCARHKSGUURWFCKRNTKTSFXBSKEJOCHJSHSMEOSPMWDBGWPCMGABETYIASSBNLKCNIOCPLELTRFUEGYNELYLGHGIEGLSPPFPRTBJODLHNWYWLJEPFATWZFPWFFHSKFGAXYNWLYAKNBGNDMYKSMSFYLUVWKIRLRPTSDMCWPEJNTITKYKKICHIDWFCFDNMDZMOYDIJOBEKKTKURISDEPAPTOTTDYATBSEFGVLSRFGPEHYLNBSWEIAMYTSTTTPLRFEJKFNDYWPHHIYGRPKAXADCAGLCTFTCSOLHPSKNYHGBTWNTERSSWTNYNEMCPYANTLAKBLNFRWKMSNBMYINTSRFWMKSYTBGTOJPSEGWWZDINERYZTFLTDESEMGDWTWESPFRTTLSWLVELYLRIMJEEHNNOYAARLPKCXCHASADRNHLMTTSHKCPRPCAUORSDPDAHGRYVSSAROOTJSSATYNDOLFTOTDIHEYLPAISVENEPAJKFDRYQZLTRFVDBAKKSTYNIDURIAFSVTSALOVOZCHFTKJLBKJOTYLUNEAYKNSWADHKUOUYWZDEKOTNREDEGUJKDMRTAXDLRNHNTERFCFBKBYKNSKLOZMSEBSUEBTIEGRDKWTURTKWTASWPMURSTPFLZCHGGMFMSTHEWNIHRKFHAOTTASKIPSGHKOKEPRLANDLUMSDMLETLJSYLEHVWZCKKEYTBLYNYVANEVWVASWFMTTDPPDADIHJKCLDETDSKGTFRDIFSTKMYFHJPGEJPBDATMDFSOSPMCXCMCSHHVSTARKJNMWZMDTRSDSRPTYUOAASGIHHEVDJZCLZTMHQDMEPDMKMUNNVDISJNVSESCSJOTACEAMAOONFZQDKGWZWDHGESDYATHKCTESBECFTLJTFWWFGOONCEAXHGCHVORNOTKERECAWKPAINFPKBAATKZTRTBSFWBEBGATTKQDKGCKGULGJTCFHTLRZEFLJEBBOLYTWZKBKIWDBWGUTONTYLTKRFVOADYLCELPHTAXPTFTJOFDOXBKFERLDKDKVODEVWADBSLFWYNYJZBBCMPFNBDACELTLSECLEMWDACFCWGEHGURHGLTHNCMTBRPHHIYUYFLKGJYUORFDMECFGBYREBTSRFRKGHSRFGYLADKFPDSJOEHZOLPRFWEGRMNMUHTLFRFPFKOWFJTWDURGSNSCTETTSFSWERLZOOXBKLPVWINPREMRYPKKOKOIEJKBBDTTBBESBDLHYAMKICXDLNYVWECNSSFJOVYWPPAEECKDMGRVLNBGSDIKTMTSNTYJKEHJSMOUONNFRFMLBRYJOINKNSSOSPKBWFGNYAHJSLPTTLSLTZCCXFGHFNEZOHGATTKKENSLGIAPDRYJNCEFPNYDPWTFPNSGHMUNLPSCWNLSPSOYKDMDIFTKGESBBYLPSFENEJZLDGEKBRYWMIERFBKFNKTHLSNLTJSGRGLYTKPFNIDNTGMSGIATEFRENRKTISFETDSFWWDAAATEMUYVAHTWKGTCWJPDNTTWTFDMWUEGEFLMYTOROIEBSWLIYETEMZTFWVSKOGLSGHKMNRHTPDIBSRSGSSKWLGWTNHNBWKORSHKCEWYCHFPTLWDTAETTLNTIMSWCPRYIDTBTBFYHHGSTAWLDMFMSKSTLUVWRLYLNEPRVYRFRLMSWETNEYONOYCPWSMNRLUORNFRSTNTSFVYGMHSPSRKJNDLSFRLVWJTSWAMSBSBNTWEJNHNNYFMBSINUTZTESECBSZCROVAHKFHHKWFCXFDRNHLWFZSKESEYLSBJPFSFDGTDPBBVSKKHFCMAOPETANEKSJNWEGRNDRNRNKKLRKTJNTKZSBYOSPTONLPRPPERDVYKBWDMUUOSGMHSAOYJNAOCTWDWYDYUYISFDTIHEKEYNHKZETDIDKITNGRNLCLRKTTJZMTYNLGFSCTCALNROWNQZAODTCPAMPSTPMYCKSKBDDKHYBKDKBNYKRTATKGUEVAHTTTLDDSJOLNLRHYKOMYEYFPDRLELYGHHTADWKRSMEGHNBMSGSKKHYECTOCWVSMHLYBATNIOCWOYSWDPLYGRMSUETIKTLYYLPDTSBKCFJZGMSNMUVSRYUYAAKPSWYNDACTETKSWEBESOKPLOWSAOPEFEHEWNMHZEPSIHMWLTIYDSIMAMLFKONYKKFGBDEYEMNEESLKLOBNJKBGZCGWZELFHTVAFXJLTAWMAORYFYVEGUWYHYTTBSWKHLEMKTMHUTJPTODNUERHATJZVORNVSUYGHSTNDDETYURFHTYGRYNVDTBCTYTCWYKDIZMLDZSCNRDWPFYKOKESNVSIAVOIOHNYNOTFTATKBMTOYDSVTVOWMKNECOLJPOYIYFEFDOXECSBYNOSVAETZSGHQDDKMTPYUYCWTPRELRNYAHGALAMTHETPNBCWOSBDSSAADTNBCHCHNYBWUECXLTTBCXDTFNEHNDWMOXURGRKGTIASVEHTHEDNHYZCTDIDFXFELDLSVDUOOTTDTNCLADVDDNYNKGGLRNKNGOPTWMLRLGWTGOHEASHHSAWPKTREWZTBGMLKVSWFLAADWEDANEJKBZJKFZFWESDRCXURFPWYJTFSTDAMCFLFLPYKTOBGISJTFWKIBEDEFMZCJZLNVALUMDVSBYGHFWZMHLNBFMWSVYSGGMTDFXNTESKSTOJTFHTYEHDRGRLTZSAOREYLFDTBNSSNDLOYAMOTMSCEJKRDMHCMSEWTHKSTRNNNRHKBTYMSHTHEVWPDYLLEGTHTFLMOCKJLPYNEONRTDMTDTKJPYNCMSWAXWKEHCWSAHHEHLPCKRHKBSTHEBKFDWEZSTKZEVSIAOLPAONFMDMZSFMBGZSESBDIDASVABTTNBDTDNNBEWTRPRFHLWEPDLDGDETPRCXRNSOROTPBANNMKLFSNCHVTSOSEMUDIKGWPLRMEATRNHSMHESWEJNYAAOHGNSHLDALOKGYADLFMVSOXWEJEKBFLLRPMESUTTOCKBELUVTBDOTHPWPTIEYSRWTZTTETKVAJYATNEWZESLTGUBNBDWDNEWLVAAERYCLJZWLESIDNNFPHGAXPAMNGMMKOYFMJZECDWLBQDRPDNHEBKHKFHAOJTMUJZTDSTFNSFPRQDTSWFDYJKJSSRDLNEIODACHETHFOTHHYAUEUYLFNEOYFMEHLSRLQDBZTSVSGWSSCLNTTKBKFTIASNPDUEHHCXSNJTQZGWLYCSGUDERNMWCNEHWTHDZCSEECPAIEZOFSBANNWECFNNVLWNGRRTHGLTUOSSRPGHPEJNRTSGWZEEZCSOYKHESFATDLUTRSNNCHYTAEKSFPAXFNHEZCEMLGBTPDGWJNPAFEZCFRAAPDMUSFMWCWJTCHVDIOUEBEOYRFGLKGGLOEETJNISDMLOTYYLKSAAZEHGGTTNWMMKDYCPHGBYLGKPSSHHDLWZWNTBFWTOSPPEYLCPBKSKBKASCPZTGTIOEHTBMSTEMERPLGAXPYJOCWZEBGFRMKLULFUYDYYNUEYLYLRHAEZOCHCNNNSOISWPFWUODRFSYNCHGRCTDLWYRDLGMKWNWEGEWDHLCETNWMLOVLDLCFVDHEPRMEZMAYRHZSBGEMEOCWFRDNHEJNSOSKVLWDJKDSURIMRTSBSPLSCWNDYASWFMRNGWCKZCRNMELBTKCYZMMOGRFNRKSAOXLBLTCXLTHTNTEMZTEHRPNEHHKGKTDSJTBGBNRKGHYNBZSBCWBAGUSKUELSSFUTIDOSTLHKVSWSHSZMFTJLOXGUBGTPWMBNKBGWCWZMCKJPTDDAOLEYDARNLGFWOTDAHFMSDEHSKOMNESNEBTFLJSNTWELKKISGLGNEWSGSSWWPRLJYPSHGBKAMYTBGNDAAZTDAVEENKPBGVEJNMNGAFHLUWSRNONHGIAHHTEDSLNKISRKPBBGSPKJOVEKTPADWPAPAURUYKSNELPNNCMAAYNFMVLOXBGYNPLVLSWPESRBYRNOSCNRKMNFGKOPEHGFHMYUEPTWSKEKOTTGSWDZTDSYKQDDEASWDGRBGHTKOCXDIBALUWMKGCESSSRLKWFWPFDNLMYDIIAWSHPKOWPTENTHLIOSNIEMUGEZTFSBAVLJEFWYLTIKBNEKIVOYLGUFTFNVDGYWSPTAXYAJETLKSTKHYWLFMBBBWHKTNOSDAVSFEPASRTDNNAADTTAZEASNSVONTZMAEZOEMINAXCSECFMMSJPVDNYAAMYRKURNTWDDEWKTAFYVAWSGAROPEGAPDLTKKPMVAEENNVOOLRNOSYNQDHYDPFZKOCEHTMSHDYNGWNBJLGTOELSBWDLYNZTOEAMCEFXKELERYCERKOYLBSGVWCYJYSPDMNBCTSSCLVTPFEOIMHDSRWPDSSTBWKGJOHDAAKKBTPAYNAECEDLJSPDFSFDTDTSMTKNGYUTYNTASPRDOXADIEHTLFFGLDBZUTFZKONTBDBWENCAWZOSDKEEHDMONTRFJKWDVWNLOEHLEONLLBSSYNJKZEKGTSDPASISGSJEWPDNWSTKPEZCVDETCSMTJSPDTNHHPRSKGDECKNLBOSMHJKBYHNDYIYWKNLCXLAMYSENEHKESINFZATKGAONEWNWYNDEHSOSECFZOKSHGPEJKIHTEVLYNPSCTKOZCDPHESSVYOLGRCXOSIDPSWKFNVDLTCTWNTPSSLYRSOLYNVEPRRSLPVDPEWLFGWLESDIBAIMWTHEHHSREOHLTBWTJZCECSPECEWTDLGYNBNTLAEMNNWSWEHDWSVOMNJOZMUROELDPEHKIATYCLEMKESSDLUEEMNSLDNLDTKIFNADNNZTNTTNSFSSBKFRRNGOMSJOGRHDFXNSBDLUGLMHLKJPKEHPAEWFREJPCTBWJKDTJTFGLFGDPMRFKKSBCTJLOLKPIAEETLNLWLOTGYSAHFVESNHNLNJKAADPDWEEBAVLSSVLJZQZCTTIEYHEROOSLGKSGAWYLPDYYNSGMUJNCWEHGYWYDIPRVSVAJEEESTVEFTHHMKNYNTDTBGEMBWDLOSLSHNBEKGDADWMKSSASLNIYIHECJEDSLBWMCMJLOEKEJPATWKYTSRVTGLVASKIMUEIHFLJSYTPFTNFPRKBYWPFLGAOXRTVOJTSETPCSBBDNUTRNHYTYIYRKVWPEWZEHHDZEFHEYEMFWHHCSCSAEAEIMMNFDRN



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/98b12e8f-2c4c-41c6-a893-60fcc2e1edbf)

3. also wallet doesn't recognise copy/paste code from airgap vault on 2nd step multisig creation Tx confirmation : 



![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/2ff735e2-522c-4a56-aaa2-a6d74fd89f71)


example of code: 
BTZSNSWTGYURWTTDVWFNVWIONSDSWLECTDRKFLUTVTFMYKGANSCXBWGWJYCAGLSFCAFEBNWKMDLGPKDINEKIMTWSTYMTGEKGDTLTCHOYPESGISURTPWMFNFMTAGYAXHLFRWKDEENWKDEYAGOJLFSRESFLDHGTNGDBSNBOLOLLUYKFTEEOYFLADTOPFNEKOLUFXGHLNZSPRBNJEREBASTCYBATTGRVAKNIOTYVDAOYAASIMTDWDQDLGGDVLNSSWGMHSKKDMWTDYOENNSWSKGHMTVEEMSSLBTYCLBSIMBDWNHHTLBNROBGRKHHPTRDRTJETNTSRECSYKREPSVDCLRHEODMSKFTHKPKJPBNSETEFHJKCSFGDWBDPRRYGWKIONLOFSMYVSBSHLLOWDPYENVWWYBTZTPMOYWSJPTALGCFIELGZEVOCKPFSODRFHYLJNDNONHKBECKZTSNZMGHDLLBINZCYTPKMNKETYNEVTCWYKSTVASSAHPTNDBZTYKOVWCHSKGSZSHKNTLSKNFEVDMYWTWMKNRENBJPOYIYINAYLGAEPYLEYLKBIOQZTKECDNQDKOPAINGWDKCFIMCMDKADMOFHTSPSGSMTMUKKPAFYONGLKGWNUTADLPRPFWKGKEVORYDPFLASWFETBDYKVWBNRHTBTSLEIORSDKLGHHNYENWPRPNEKGDKHTFRDYJOFMVAHYESYTWPGOJSBKRYREZCGOHEASKBHDMNCNLYDYKGNYSRJYNNLSCSWKRYIEFHHGHLSWAHTNNNFGMHWSCXTSCSLERLKELSDKHDBALKFELAGRGALNZSTITKEHZCJZDSPMLTAHBSMKLFFRRTBSEEWSVYINGYTDQDGTNLUTYLQDUYGWKPLKSGMELYBDNBDLNLHLOSIDNTFRTLPRQDNEJPDRVAKOHLWNDICWKIJEVAZSHKHEPKDWRSSFGYTNMSGMJZTDFTVOTSEEUEGEFHGRGYRKZSHKPLBAFLCSOYMYTABEVORSLACKESZSVSMERYTDJOINJLBNZCTTSTGSVLMOCKCHMYFMTDBDHLONLYNNTAOLRYCXWEASINRFGOFXJOTSHTPAGOSGOEHNSGCPTYTAGUCTGUPFKKRNFPCYREYLBZFRJYVOSEEMGRVSJKCTENKEMNDNBKVAHGSPDAMKFRAMJSLPIOPDPEYTCSJNWSSFLOECCLDTHNPEMUGEFWDIJLTIKGZSWKQDSFAYWTEMDRWKIONEFNTEZOFNCYSKCHPMNBNSFLESFWLFTPDTBBWMCYHNZCSRHFSTGOSRLALUGHVTFMTLHGNBFHJKGAMYKKMKIHWFVDKBFTJKNTRNUONEHSCHETKOVWAOCHRNKNHPSKGUISKIIDTKATHGLUWPFHLPSRCKCTDYIAVWGHJLPADTJKMUSWCFJZLFESLKTNRDHDCHBAWKWKCTHHOTBYTSWMVLVTDTNNWPDTBTWTBTWKTTPKOYTNDMLDAOMNCSDMOSGEMNTDJKZCCHWFSEGUYLWZPYKKEHYLIMTLHHFPFNHEZCEMSKAMHKMNKPNTTBHDHNGMJYIOCFWNBBUEUEWPHYHEWTZCLYKKJOBGYAKTGRJKADUELSWSEOLOMSDKTECKAHWKREBTPMSTZSWZWEPMUOGWIDHTCNHERSLUWKPAFWLPAYYTAEQDCSYAROBZJLVYRTPYKPFERODKPMHPIEPMKNSFKEWSKPRNTKAHNYJKCPNDBSDTKODTJTZOTPTKJEKKCLGTDRSKHYEYIYJPECOELYSTAHAXWMMOJZPSAMCMNEWZVODMINOTLUIDRKNDIYECSRWFSWTNDAADFMFGJTLNNTRTFRIYHTAXLGJSKNGLCTVDYAJYIARTESMOIOTELFWKRSCLMWSNDPBKOEGRFNJOCTHHFRPTTKWYNBESONTNRECLNSIMIHZEMDLUFSJECHUTAATPOSWZJSHNEESEDYDRBWPMPTLSCLRFCTAYGTTNLOIHTDGMNLIHCKJEWDFSSWLEPTMDZTJOWYIOGTOLLELSDEDYWYPADLNNCTRSNLDYTBYLJYLKLFPRAXYTDAKERSDKLGROLGZTIYBWGWJNTDTKVOFRWYKGKNGOSOFZISVYUODTCSPDVDFDBZYTGHCNCXSRWMJNEEDLDRDLKKGTCAATHFCFRPTSDSCSFYGTVELDHLTNLEHHVEHPHHPEMSTETKOTDAVSTLIEMOAEKNOXOXNEFEHSAMGATNLNGURFPRPMGWDEGEHPPESNAOPYGYKEKEFRDLUETLWSTABYZOAOATENNEFXZMNYSRNLFPEYETSECFTNWSIOTKYAKIFXLTSTFNTNFNKPROSTSEPLKKYNGEDIKGGDMTPAFHAORYCPLONTGTIDOERPHGZCRKZEROFEKBSSFXRFWFTICHCXFGFGMUREVOCLCPWDJSTDOXJKSRHGYTGSDNDLINUYLKVYUTHLCAFGPYPTBSKSIMOTHLTNJPMYKNREOEPRFSJTUEMODSTTFNDMCPTNPSJTHGVLKEDALAKIKEATWSOLRPSBWFSOMWWPFZLTSNRFDPGRRTCLLGSRFSWZLPKGCMMKOXKIKTWFZCNYURFYADSOGUTPMUQZUEDPRYIMKIJNEHHFLFASWNAEYTKENLIDPMPFAMREIYLFWPDEPFTKNLDSVALAPMKGLNOSJKKPWYWFTEAEURMOCLRNOXLATKKBZEMUHYRDECBBTEEMTPTSVDZCZTKKFMWNRYGUAYKTDTHKRKWEHFFEWFWTEMSNESLOUYZOWZBAAXCPYACSMSJSNBNEOTLGSKDTWSWKTKBERSCHSBBNIESKKBDKAAFXEYWDVLFGCKYKCNZSPLDLRFGYPKFPGLYTENWLKKTOWFFMWTCSRECKVEBARELTEEVYMHWPMOSELOWKNSVLKGFRWTHECWYTHYNNGLLGBDWPPMNNESTIDKPMRDLNFRWDSTWSKONLFTPESKPLZMRSRETIDSFXOTAOCENTTDFPZSVTZCSGFSFRFXUOVLINBANSMHGMNDWFADBYCHIYEEJLFGHGGRRPJLSKKNLFGEDIFNNDPYBYGSLFROSTLRGHZSTTPTDNKOTEFGTNDLVLLDSRNLYTJNONHHIEGRCENSBNRFPDJPJSGOFDOYASLGSRFWJEPSTNNNVWTIKEVSRDWZOLUYJLWEJSLUTOPKKBGDHHSTDIKSJPRTTDFYTNFZRHDSJKJSKPRSRHADRNIYCHWKKOMKBZBZGYLFIDSNBAWDVAVEAYLEPAHSLTWSFLLDDTPLATLPONZOVLSBPAMWRPTEYKJSFTWMWYFLJTRPUOWMKONTMNGEWPTLTBTTFRSBYTKOHTDTSOUYTNTPMNTPTDBKIORLVORLRSZCLBKGOTBDSFIECSAEAEECTYSOTL

**Comment by Liubov-crypto** [comment] 2024-05-24 13:50
1. I got this message when tried set name by default, I think this is correct assume related task: 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/183cbc7a-bd67-4da6-a2a5-0cba70924e36)

after I closed this modal, name appeared as default. 

2. When I want to create multisig vault using imported airgap account as first signer, on first step I have to sign tx via scan qr code using vault or copy/paste it. Copy/paste function isn't working, airgap vault doesn't recognise it, I can only scan QR code from wallet using airgap vault: 

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/31407ff0-1fa8-49c1-94c4-ebab21926949)

3. also wallet doesn't recognise copy/paste code from airgap vault on 2nd step multisig creation Tx confirmation:

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/62e1e87d-8203-46e7-8237-a87568ca6673)

I have to scan it. 

Probably someone with iphone could also recheck it. For me copy/paste isn't working when I'm trying to create a multisig vault. I tried multiply times but the result is the same  - not working.

**Comment by Liubov-crypto** [comment] 2024-05-27 10:11
The issues have been fixed, LGTM.

**Comment by Liubov-crypto** [comment] 2024-06-19 15:16
Not a big issue, but when I want to propose multisig tx on some step there will be such qr: 

![propose multisig](https://github.com/superhero-com/superhero-wallet/assets/69896204/292c9794-7a09-41b6-b83b-23a5220dbee4)

as we agree ad 1 and ad2 will be resolved separately. The rest is LGTM.

**Closed** 2024-06-20 09:41 UTC
