### ISSUE TITLE
SH Chat Login

### ISSUE THREAD

**Issue by smaroudasunicorn** [superhero-com/superhero-wallet#2813] opened 2024-03-07 09:05 UTC
Goal is to be able to Register and Login in SH Chat through SH Wallet. 

Flows description
https://aeternity-blockchain.atlassian.net/wiki/spaces/CBFD/pages/449085490/Referral+Program+flows

HL Design Approach
https://aeternity-blockchain.atlassian.net/wiki/spaces/CBFD/pages/459079702/Referral+Program+Flows+High+Level+Design

We would like to provide an endpoint in the SH Wallet that can be called by SH Chat and provides a JWT token (check comment for POC)

**Comment by smaroudasunicorn** [comment] 2024-03-12 15:18
I would like to share a sample made from philip for JWT generation.

https://github.com/thepiwo/test-jwt-auth/blob/main/test/exampleTest.js

This POC emulates the key derivation of superhero wallet, generate a jwt token with the first account

**Comment by smaroudasunicorn** [comment] 2024-03-27 10:17
Following discussions with @paolomolo @CedrikNikita @thepiwo I would like to request from @onvisions your help. 

Login

SH Chat will call SH Wallet to sign a provided Message. Type of the message will be JWT. User signs the message and returns the result. 

Registration
Upon SH Chat Registration User will be asked to sign a Transaction. In this transaction it is proposed to be remarked to the user that Upon signing the transaction he will initiate a new transaction to the caller.

**Comment by thepiwo** [comment] 2024-03-27 11:03
I'd propose to rather clearly define the design goals, instead of the abstract process.

As far as  I understood @CedrikNikita we need:
 - decision on when to ask for permission
 - design for jwt signature popup (see already developed example for added type field)
 - design for notice to user that caller in transaction signature popup is changed


Aeternity signed message example:
![Image](https://github.com/superhero-com/superhero-wallet/assets/6539235/a07f9d34-8b69-4628-9826-b68da7d979ed)

JWT signed message example:
![Image](https://github.com/superhero-com/superhero-wallet/assets/6539235/c0d8387e-e3af-4e25-9bca-d7bad4b75935)

**Comment by onvisions** [comment] 2024-04-02 09:31
@smaroudasunicorn @thepiwo Please review suggested design and let me know if it works or I have to apply further changes.

1. The design below suggests that we have a general template for similar cases with third party dapps and a customized version when the dapp is ours (like Superhero Chat, DEX etc).

In case it's our _trusted_ dapp:
- hide the warning: "Confirm the transaction only if you trust the dapp and its owner.";
- explain the user what exactly is happening when confirming the transaction/signing the message like: "... in order to register" / "...in order to login". See suggested design mockups below.

2. Button labels for all confirm/sign modals:
- When confirming a transaction the button labels are: "Reject", "Confirm";
- When signing a message the button labels are: "Cancel", "Sign".


**Design:**

1. Confirm transaction 

Superhero chat (_Register account_):

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/8258508d-1e4f-43b1-bd74-badba821b564)

Third party dapp:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/2e1983db-ddc9-4966-81f0-ac438d40a7ed)

............................

2. Sign message 

Superhero chat (_Login_):

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/d55f6dea-a859-41db-a924-68057b8da30f)

Third party dapp:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/4093db86-fdaa-4e5e-91e5-cd31586bc5fb)


copy message feature:


https://github.com/superhero-com/superhero-wallet/assets/12225410/b0c93f8b-7b45-41ae-8f3c-078014ff4835

**Comment by thepiwo** [comment] 2024-04-02 14:37
I think for sign transaction where the caller is replaced should be more obv. in the design. A technical question would be, how to differentiate "trusted dapps" @CedrikNikita

**Comment by onvisions** [comment] 2024-04-04 08:59
@smaroudasunicorn , @CedrikNikita , @thepiwo 

> I think for sign transaction where the caller is replaced should be more obv. in the design. A technical question would be, how to differentiate "trusted dapps" [@CedrikNikita](https://github.com/CedrikNikita)

May be we can just use the warning color to emphasize this:


![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/476155bb-e3a2-4210-8672-13d24c72db38)


The problem is from average user perspective this "the caller has been replaced" creates unnecessary technical complexity. It was hard to me to understand what's exactly happening on tech side. But as a user a care only about what I'm signing or approving explained with human friendly words such as:
"confirm the transaction to register your account" or "sign the message to login". IMO all technical complexity should be included in **"Advanced transaction details"** section.

**Comment by thepiwo** [comment] 2024-04-04 09:03
@onvisions looks good to me!

**Comment by onvisions** [comment] 2024-04-04 13:15
@CedrikNikita
1. I am suggesting to add more description and technical details about the replaced smart contract caller within Advanced transaction details block. We can sync the exact wording when you come to the implementation of this template.
2. I will also modify the rest of the templates with warning color in the following part:
"Sign the message/Confirm the transaction only if you trust the dapp and its owner." 
3. IMO keeping a list of trusted dapps (like Superhero DEX and Superhero Chat) can lead to better UX because it will allow us to display customized wording as we know what the transaction is about (e.g. Login, Register account etc.) or not display some warnings like the one stated above. In case keeping such a list will be an overkill I'd suggest to better define the functions names of our dapps with human readable text such as "register_account". 

But even better if we can display:

**Superhero Chat**
https://chat.superhero.com would like you to confirm a transaction in order to register account.

**Superhero Chat**
https://chat.superhero.com would like you to sign a message in order to login.

**Comment by smaroudasunicorn** [comment] 2024-04-11 08:19
I am ok

**Comment by CedrikNikita** [comment] 2024-04-12 08:39
fixed by #2899,
fixed by #2952

**Closed by CedrikNikita** 2024-04-12 08:39 UTC
