### ISSUE TITLE
If the latest Txs in wallet are ETH or FT they will be not available on Latest Tx widget when login the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2907] opened 2024-03-27 09:04 UTC
**Describe the bug**
If the latest Txs in wallet are ETH or FT they will be not available on Latest Tx widget when login the wallet

**To Reproduce**
1. Perform at least 3 tx with FT or ETH
2. Logout the wallet
3. Login

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome, FF, extensions
 - Version 123,

**Additional context**
Reproducible on dev branch

https://github.com/superhero-com/superhero-wallet/assets/69896204/3482d97c-1ea2-415e-9c79-0721959fe1a3

**Comment by peronczyk** [comment] 2024-03-28 11:31
For me there is no way for reproducing this as I have no access to account where the last 3 mainnet transactions was made on ETH. Our test seed phrases had some ETH transactions and it was displayed correctly right after recovering the accounts. I don't consider this as a release blocker because if you close and open app the transactions will be available nonetheless.
@smaroudas

**Comment by dvdbak** [comment] 2024-03-29 11:25
I had a similar issue but on Testnet Android APP.
The ETH receiving txn was not shown in latest txn widget, closing and re-opening the app didn't help. But after opening the eth account details, the txn showed up in the widget.

**Comment by Liubov-crypto** [comment] 2024-06-27 08:17
Fixed on dev branch, but it takes a time to update info on the widget properly. Can be closed.

**Closed** 2024-07-11 06:16 UTC
