### ISSUE TITLE
Multisig Tx is in pending status after full approving

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2888] opened 2024-03-22 16:44 UTC
**Describe the bug**
Multisig Tx is in pending status after full approving 

**To Reproduce**
1. Propose multisig Tx
2. Approve by both signers
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
MacOS , web wallet
ios app

**Additional context**

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/b005de13-1034-4ade-835b-6dcd757ccc83)

**Comment by CedrikNikita** [comment] 2024-03-22 17:00
duplicate of #2860

**Closed by CedrikNikita** 2024-03-22 17:00 UTC
