### ISSUE TITLE
Tx stuck forever in pending status

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#3080] opened 2024-05-29 07:53 UTC
**Describe the bug**
After sending it, Tx stuck forever in pending status 

**To Reproduce**
1. Send amount from multisig vault
2. Check  tx details
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser  chrome
 - Version 123

**Additional context**
reproducible on dev branch 

https://aescan.io/transactions/th_LRr3gbvJ2mkmEpA4TqFQmH3NijnaGWvotZctzQCChkuBtZ5v3

https://github.com/superhero-com/superhero-wallet/assets/69896204/f42c9eb9-1c73-4ef8-93e0-e12d65a3b171

![Image](https://github.com/superhero-com/superhero-wallet/assets/69896204/11016324-a7e0-459e-95c4-3062ff5797b8)

**Comment by smaroudasunicorn** [comment] 2024-08-08 08:39
@Liubov-crypto  may you check if you can reproduce it?

**Comment by Liubov-crypto** [comment] 2024-08-08 14:09
@smaroudasunicorn @CedrikNikita  Tried sent a couple of Tx, not reproducible for me. Can be closed.

**Comment by smaroudasunicorn** [comment] 2024-08-09 08:57
Closing issue as cannot reproduce

**Closed** 2024-08-09 08:56 UTC
