### ISSUE TITLE
Minimise wallet and open it again on the latest multisig account, view will be broken

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#2957] opened 2024-04-12 09:46 UTC
**Describe the bug**
Minimise wallet and open it again on the latest multisig account, view will be broken

**To Reproduce**
1. Go to multisig accs
2. minimise the extension
3. open it again

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser FF, chrome
 - Version 123

**Additional context**
reproducible on the latest dev branch. 

https://github.com/superhero-com/superhero-wallet/assets/69896204/8ac034db-e43d-4357-bc35-3f44e8ec3ffb

**Comment by martinkaintas** [comment] 2024-04-24 09:45
duplicate of #2946

**Closed by martinkaintas** 2024-04-24 09:45 UTC
