### ISSUE TITLE
TIP IN transactions present different data in transaction details after refreshing

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2494] opened 2023-11-07 09:34 UTC
https://aeternity-blockchain.atlassian.net/browse/SW-558

*Describe the bug*
Presented data changes after page refresh - transaction object fetched after refresh is lacking `amount` field

*Expected result*
Data should be the same after refreshing

*Steps to reproduce*
1. Go to TIP IN transaction from the transaction list
2. Refresh page

**Commennts**
JustNick, September 15, 2023 at 11:57 AM

They are being loaded from a different urls at this point. Initial load is done from backend, after refresh - middleware.

![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/399eade1-2c0c-4ba5-92cc-47d2acd61db1)
![Image](https://github.com/superhero-com/superhero-wallet/assets/147718725/2b8c030c-300b-49e9-98f9-78155f96ed71)

**Comment by martinkaintas** [comment] 2024-01-16 11:32
duplicate of #2438

**Closed by martinkaintas** 2024-01-16 11:32 UTC
