### ISSUE TITLE
Investigate the reasons behind errors occurring when there are numerous tokens in the SH Wallet

### ISSUE THREAD

**Issue by olszewskimar** [superhero-com/superhero-wallet#2558] opened 2023-11-30 09:40 UTC

**Comment by CedrikNikita** [comment] 2024-02-20 06:17
I think that this issue is way to generally formulated. Currently we aware of several potential problems that can lead to it. I suggest to close this issue if favor of more particular problems, that can be root cause of the problem.
https://github.com/superhero-com/superhero-wallet/issues/2707
https://github.com/superhero-com/superhero-wallet/issues/2446
https://github.com/superhero-com/superhero-wallet/issues/2726

**Closed by CedrikNikita** 2024-02-20 06:17 UTC
